services:
  postgresdb:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=tutopedia_db
      - PGUSER=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  liquibase:
    image: liquibase
    volumes:
      - /Users/rudiwelter/Workdir/Tut-O-Pedia/Tut-O-Pedia_Docker_Deploy/db/:/db/
    depends_on:
      postgresdb:
        condition: service_healthy
    command: --defaults-file=/db/local/liquibase.properties update
    # command: /bin/bash -c "sleep infinity"

  backend:
    image: ruwel123/tutopediabackend
    ports:
      - 8080:8080
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      postgresdb:
        condition: service_healthy

  frontend:
    image: ruwel123/tutopediafrontend
    ports:
      - 4000:3000
    depends_on:
      backend:
        condition: service_healthy

volumes:
  pgdata:
    driver: local
